### ISSUE TITLE
Computer ON status reported incorrectly on mobile device

### ISSUE THREAD

**Issue by qtiki** [TylerPalko/Is-My-Computer-ON#1]
When viewing the computer ON status from a mobile device the status is incorrectly reported.

**Steps to reproduce:**

1. Turn off your computer
2. Navigate to https://tylerpalko.github.io/Is-My-Computer-ON/ on your mobile device
3. Observe the page incorrectly displaying `Yes.` for the computer ON status

**Expected behaviour:**

The page should report the computer ON status as `No.` when viewed from your mobile device while your computer is in fact turned off.

**Comment by TylerPalko** [comment]
Thank you for taking your time to report this issue. We are actively working on this, and it will be fixed as soon as possible.

**Comment by TylerPalko** [comment]
I was gonna do something funny but I couldn't think of anything
